### ISSUE TITLE
[question] AwayFL loader or player?

### ISSUE THREAD

**Issue by ousia** [n0samu/n0samu.github.io#1]
@n0samu,

many thanks for your info on the AwayFL player.

I have just discovered the project from AwayFL and I see that  [this repo](https://github.com/awayfl/away-player-embed) is almost two years old.

Sorry for the stupid remark, but I wonder whether [other recently updated repos](https://github.com/awayfl/) couldn’t be used here.

Many thanks for your help.

**Comment by n0samu** [comment]
No worries, it's a good question. I've been helping out with both the Ruffle and AwayFL projects recently. The away-player-embed repo has been the user-facing method to get AwayFL up and running, but we are working on moving that functionality to [awayfl-player](https://github.com/awayfl/awayfl-player) and writing updated usage instructions. I recommend watching that repo and waiting for now.

After that, we're also planning to update the [online demo for AwayFL](https://exponenta.games/games/AFL/) since that is very outdated too.
